import java.io.BufferedReader;
import java.io.FileReader;
import java.io.PrintWriter;

import javax.swing.*;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;

//import user_gui.UserGUI;
import java.awt.SystemColor;

/**
 *
 * @author noname
 */
public class listing extends JFrame {

    DefaultListModel<String> listModel;
    boolean flag;//used to stop multiple entries
    public listing() {
    	setBackground(SystemColor.inactiveCaption);
        initComponents();
        listModel = new DefaultListModel<>();
        flag = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(SystemColor.inactiveCaption);
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jList1.setBackground(UIManager.getColor("InternalFrame.activeTitleGradient"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(SystemColor.activeCaption);
        jPanel2.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Listing System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(244, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 502, GroupLayout.PREFERRED_SIZE)
        			.addGap(211))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBackground(Color.PINK);

        jList1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(jList1);
        WRITE = new javax.swing.JButton();
        
                WRITE.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
                WRITE.setText("WRITE TO FILE");
                WRITE.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        WRITEActionPerformed(evt);
                    }
                });
        ADD = new javax.swing.JButton();
        
                ADD.setFont(new Font("Segoe UI", Font.BOLD,   20)); // NOI18N
                ADD.setText("ADD DATA");
                ADD.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ADDActionPerformed(evt);
                    }
                });
        READ = new javax.swing.JButton();
        
                READ.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
                READ.setText("READ DATA");
                READ.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        READActionPerformed(evt);
                    }
                });
        REMOVE = new javax.swing.JButton();
        
                REMOVE.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
                REMOVE.setText("REMOVE DATA");
                REMOVE.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        REMOVEActionPerformed(evt);
                    }
                });
        jTextField1 = new javax.swing.JTextField();
        
                jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(52)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 259, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        					.addComponent(WRITE)
        					.addGap(55)
        					.addComponent(READ, GroupLayout.PREFERRED_SIZE, 169, GroupLayout.PREFERRED_SIZE)
        					.addGap(75))
        				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        					.addComponent(REMOVE)
        					.addGap(186))
        				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        					.addComponent(ADD)
        					.addGap(210))
        				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE)
        					.addGap(133))))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(19)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(REMOVE)
        					.addGap(18)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(READ)
        						.addComponent(WRITE))
        					.addGap(18)
        					.addComponent(ADD)
        					.addGap(206))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 389, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(52, Short.MAX_VALUE))))
        );
        jPanel3.setLayout(jPanel3Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 915, GroupLayout.PREFERRED_SIZE)
        			.addGap(20))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 435, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WRITEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WRITEActionPerformed
        //writing to text file
    	JOptionPane.showMessageDialog(listing.this, "Writing...");
        int val = jList1.getModel().getSize();
        PrintWriter writer = null;
        try{
            writer = new PrintWriter("data.txt");
            writer.println(val);
            for(int i = 0; i < val; i++){
                writer.println(jList1.getModel().getElementAt(i));
            }
        }catch(Exception e){
            System.out.println(" " + e);
        }finally{
            writer.close();
        }
    }//GEN-LAST:event_WRITEActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        String str = jTextField1.getText();
        if(str.equals("") || str.equalsIgnoreCase("Type here")){
            jTextField1.setText("Type here");
        }else{
            listModel.addElement(str);//add string to list model
            jList1.setModel(listModel);//set list model to jlist
            jTextField1.setText("");//clear text field
            flag = true;
        }
    }//GEN-LAST:event_ADDActionPerformed

    private void REMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEActionPerformed
        //will remove data
    	JOptionPane.showMessageDialog(listing.this, "Removing...");
        listModel.removeAllElements();
        jList1.setModel(listModel);
    }//GEN-LAST:event_REMOVEActionPerformed

    private void READActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_READActionPerformed
        //load data from list to text file
    	JOptionPane.showMessageDialog(listing.this, "Reading...");
        if(flag){
        BufferedReader br = null;
        try{
            br = new BufferedReader(new FileReader("data.txt"));
            int val = Integer.parseInt(br.readLine());//read the first line from file
            for(int i = 0; i < val; i++){
                String ss = br.readLine();//read data from file
                listModel.addElement(ss);//add data to list model object
            }
            jList1.setModel(listModel);//store listmodel to list
            flag = false;
        }catch(Exception e){
            System.out.println(" " + e);
        }finally{
            try{
                br.close();
            }catch(Exception e){
                System.out.println(" " + e); 
            }
         }
        }
    }//GEN-LAST:event_READActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton READ;
    private javax.swing.JButton REMOVE;
    private javax.swing.JButton WRITE;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}